version: '3'
services:
  frontend:
    build:
      context: ./FrontEnd  
    ports:
      - "5173:5173"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend  
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "buypakistan"
      MYSQL_USER: "talha"
      MYSQL_HOST: "65.21.2.143"
    
